language: node_js

node_js:
  - v12
  - v11
  - v10
  - v9
  - v8
cache: yarn
install:
  - yarn

before_script:
  - yarn lint

script:
  - yarn build chrome
  - yarn build firefox
  - yarn build opera
