language: node_js

node_js:
  - v11
  - v10
  - v9
  - v8
cache: npm

script:
  - npm run build chrome
  - npm run build firefox
  - npm run build opera
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: packages/*
  skip_cleanup: true
  draft: true
  on:
    tags: true