language: node_js
node_js:
  - v11
  - v10
  - v9
  - v8
cache:
  directories:
    -node_modules
install:
  - npm install
script:
  - npm run build chrome
  - npm run build firefox
  - npm run build opera